### ISSUE TITLE
Question about the baseline

### ISSUE THREAD

**Issue by Dhidbsixh** [Kunhao-Liu/StyleRF#11]
Hi, very thanks for your work! In the paper, your work choose 《 Stylizing 3d scene via implicit representation and hypernetwork》as a baseline, the code of this baseline is based on NeRF++, and the dataset is Tanks&Templets. So I'd like to know what changes you made to the NeRF++ code to make it possible to run on the LLFF dataset？ Thanks a lot !

**Comment by Kunhao-Liu** [comment]
Hi, we treat the LLFF dataset as custom scenes and use [the NeRF++ code](https://github.com/Kai-46/nerfplusplus#generate-camera-parameters-intrinsics-and-poses-with-colmap-sfm) to generate the camera poses in their format. Then the LLFF dataset can be used to train NeRF++.

**Comment by jly0810** [comment]
> Hi, we treat the LLFF dataset as custom scenes and use [the NeRF++ code](https://github.com/Kai-46/nerfplusplus#generate-camera-parameters-intrinsics-and-poses-with-colmap-sfm) to generate the camera poses in their format. Then the LLFF dataset can be used to train NeRF++.

您好，我最近在测试LSNV的效果，但该工作使用的数据集是特殊格式的tankandtemple，我想知道您是怎么把llff数据集转换成这种格式的，非常感谢！
