### ISSUE TITLE
Question about style image name used in the paper

### ISSUE THREAD

**Issue by ruanchunqing7** [Kunhao-Liu/StyleRF#13]
Hi, very thanks for your work!
I want to replicate your work. Could you please tell me the names of the style images you used in the paper?

Thank you very much!

**Comment by Kunhao-Liu** [comment]
Hi, all the style images can be accessed in [this link](https://drive.google.com/drive/folders/14hvVwFwtFm3ReEMVOvrB4kJx6vbdD_ru?usp=sharing).
