### ISSUE TITLE
Question for room dataset

### ISSUE THREAD

**Issue by SCUTykLin** [Kunhao-Liu/StyleRF#25]
We run your code on llff room dataset. And we use the images_8(downsample 8 times). In the second stage, train_feature.py can only achieve 15 PSNR. Does it normal? In the first stage, train.py can achieve 35 PSNR.

**Comment by Kunhao-Liu** [comment]
Hi, it is not normal. You can try training with images_4.

**Comment by SCUTykLin** [comment]
Thanks for your reply. Another question, do u try replica dataset? How large RAM does it need? I use your model as baseline to compare

**Comment by SCUTykLin** [comment]
I try blender dataset and my RAM is not enough(64G RAM).

**Comment by Kunhao-Liu** [comment]
If the RAM is not enough, you can use only half of the images or even fewer in the second stage. The performance won't be affected too much.
