### ISSUE TITLE
Question for the zero-shot?

### ISSUE THREAD

**Issue by SCUTykLin** [Kunhao-Liu/StyleRF#26]
May I ask where the zero-shot of your paper is presented? StyleRF, like other papers, is a two-stage training. I'm very confused about the zero-shot. Thanks

**Comment by Kunhao-Liu** [comment]
Hi, StyleRF is zero-shot to styles, meaning it does not need to be retrained for unseen new styles. Other method like ARF, styliednerf, snerf, need to be retrained for new styles.

**Comment by SCUTykLin** [comment]
Thanks for your reply, but I saw your paper need to train. In section 3:
![image](https://github.com/Kunhao-Liu/StyleRF/assets/34080744/7038cd7e-3412-4db3-acae-50608d18971e)

**Comment by Kunhao-Liu** [comment]
After this training stage, StyleRF does not need to be trained again for new styles, while other methods need to be retrained. 

StyleRF can transfer styles it does not encounter during training.
