### ISSUE TITLE
Testing on nerf_synthetic. (blender.py‘s code of the data_loader)

### ISSUE THREAD

**Issue by HeChengy** [Kunhao-Liu/StyleRF#27]
Hello, when I try to conduct testing experiments on the nerf_synthetic dataset, I encountered an error saying 'BlenderDataset' object has no attribute 'render_path'. It seems that there is a missing part in the blender.py code of the data_loader. Could you please share the code for testing on nerf_synthetic? Thank you

**Comment by Kunhao-Liu** [comment]
Hi, you can set `render_test=1` and `render_path=0` in `test_style.sh`. `render_path` is only valid for LLFF dataset.
