### ISSUE TITLE
Support for Object Inputs (Rendered or Mesh) **urgent**

### ISSUE THREAD

**Issue by ipekoztas** [Kunhao-Liu/StyleRF#33]
Hi,

Can this project accept objects as inputs for stylization? Specifically:

Rendered objects (e.g., GIF or MP4 files)
Mesh files (.obj or .ply files)
If yes, how can I integrate them? If not, what would be required to modify the pipeline?

I’d appreciate a quick response as this is urgent.

Thank you!

**Comment by Kunhao-Liu** [comment]
Hi, you can convert the objects you want to stylize to the format of [nerf_synthetic](https://drive.google.com/drive/folders/128yBriW1IG_3NJ5Rp7APSTZsJqdJdfc1) dataset. Then you can run the pipeline under the nerf_synthetic setting.

**Comment by ipekoztas** [comment]
Do you have any suggestions about converting the objects to nerf synthetic dataset format? Thank you.
