### ISSUE TITLE
About results on consistency

### ISSUE THREAD

**Issue by xingy038** [Kunhao-Liu/StyleRF#6]
Hi, thanks for your valuable work. Can you tell me how you achieved these results in the paper? I don't seem to find it in the code.

**Comment by Kunhao-Liu** [comment]
Hi, for the multi-view consistency evaluation, we use [RAFT](https://github.com/princeton-vl/RAFT) to compute the optical flow. Then, we use [softmax-splatting](https://github.com/sniklaus/softmax-splatting) to warp the image and get the mask. Finally, we compute the RMSE score and the [LPIPS](https://github.com/richzhang/PerceptualSimilarity) score between the warped image and the target image.
