### ISSUE TITLE
Question about which 2 frames are selected to compute short/long range consistency

### ISSUE THREAD

**Issue by Dhidbsixh** [Kunhao-Liu/StyleRF#8]
Hi, very thanks for your work! In the paper, I would like to know how pairs of images are selected for calculating short/long range consistency in the paper, for example, in the LLFF dataset, are the images selected in the order in which they are named?

**Comment by ruanchunqing7** [comment]
I have the same problem.
Also, I have another problem. In the compute metrics, I don't see how to compute the RMSE, could you please tell me how to compute the RMSE?

**Comment by Kunhao-Liu** [comment]
Hi, we use two frames with close camera poses to compute the short-range consistency and frames with distant camera poses to compute the long-range consistency. The frame pairs are manually selected and differ in different scenes.

**Comment by Kunhao-Liu** [comment]
> I have the same problem. Also, I have another problem. In the compute metrics, I don't see how to compute the RMSE, could you please tell me how to compute the RMSE?

Hi, you can refer to https://discuss.pytorch.org/t/rmse-loss-function/16540.

**Comment by ruanchunqing7** [comment]
> > I have the same problem. Also, I have another problem. In the compute metrics, I don't see how to compute the RMSE, could you please tell me how to compute the RMSE?
> 
> Hi, you can refer to https://discuss.pytorch.org/t/rmse-loss-function/16540.

Thank you for your response. I mean, In your implementation code, how to calculate the RMSE in your paper, I do not see the relevant implementation.
<img width="674" alt="image" src="https://github.com/Kunhao-Liu/StyleRF/assets/55775666/3611bfca-2643-4695-96e4-c93c138fe36b">

**Comment by ruanchunqing7** [comment]
> Hi, we use two frames with close camera poses to compute the short-range consistency and frames with distant camera poses to compute the long-range consistency. The frame pairs are manually selected and differ in different scenes.

Thank you very much for your response. If we select deferent frames with you when compute the long-range consistency, will the metrics we get be very different from the LPIPS in the paper?

**Comment by ruanchunqing7** [comment]
> Hi, very thanks for your work! In the paper, I would like to know how pairs of images are selected for calculating short/long range consistency in the paper, for example, in the LLFF dataset, are the images selected in the order in which they are named?

Hello,

I have not found the implementation code corresponding to table 1, may I ask if you have found it?
Thank you very much!
